# Generated by Django 5.0.6 on 2024-07-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lutsImage1',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage10',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage11',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage12',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage13',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage14',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage15',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage16',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage17',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage18',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage19',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage2',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage3',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage4',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage5',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage6',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage7',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage8',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='lutsImage9',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
    ]
